### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [svenslaggare/termcalc#1]
Dear Mr. Jansson,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by svenslaggare** [comment]
See https://github.com/svenslaggare/termcalc/releases/tag/1.0.0

**Comment by sergeevabc** [comment]
Thank you for a quick reply, Mr. Jansson.
It works as expected, however I was a bit confused by the need to enter a colon before ```quit```.

**Comment by sergeevabc** [comment]
By the way, app crashes after using command ```:polar```.

**Comment by svenslaggare** [comment]
Fixed, download the 1.0.0 release again.

**Comment by sergeevabc** [comment]
Is there a way to calculate ```335-3%```?
